import requests
import json

# Your Carbone API key (Bearer token)
access_token = "eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxMTI2MDAyMjg2OTYzODg2NDczIiwiYXVkIjoiY2FyYm9uZSIsImV4cCI6MjQwNTk0NTgwNiwiZGF0YSI6eyJ0eXBlIjoicHJvZCJ9fQ.AH3LrsZ92_uHFwm3H7xvUs4UkH39FOz7qw-GT0Dr67tMGqMDkwhQqBneudcqcJwsVjiij8kI0WmX1g7IwMu8MCfyAAyVNjriZPY_O3tZlA42bClXigwUlYbtt6qUiVFNK9EmAQOfVjEfRq2peT75LaLUMKG4k1oK_iD92cNhNQkPUYsr"

# Template ID (must already be uploaded to your Carbone account)
template_id = "11dc5f880d56434b9ffe684b4eb5e1ebaf1e98ec9c05b5534c6f02a751cfbd59"

# JSON payload (data for the template)
json_payload = json.dumps(
    {
        "data": {
            "TS-ID": "202507TSTSTAb211053c",
            "BU_Header_Logo": "",
            "Business_Unit": "Test BU",
            "Consultant": "TESTDUM1 TESTDUM1",
            "Reporting_month_new": "Jul-2025",
            "Customer_name": "New test client",
            "Total_nr_hours_this_period": "72.00",
            "Total_nr_days_this_period": "9.00",
            "Nr_days_normal_this_period": "8.00",
            "Nr_days_OT1_this_period": "0.50",
            "Nr_days_OT2_this_period": "0.50",
            "Cost_NMT_Act": "\u20ac250.00",
            "Related_Project_TS_Calendars": [
                {
                    "Project_TS_Calendar_ID": "e0a835e5",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-01",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
                {
                    "Project_TS_Calendar_ID": "c3b69f0f",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-02",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
                {
                    "Project_TS_Calendar_ID": "c9c1580f",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-03",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
                {
                    "Project_TS_Calendar_ID": "7f19415d",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-04",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
                {
                    "Project_TS_Calendar_ID": "9ede8bfa",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-05",
                    "Nr_hours_normal": 0.0,
                    "Nr_hours_OT1": 4.0,
                    "Nr_hours_OT2": null,
                    "Comment": "Zaterdag",
                    "Update": null,
                    "Last_change": "2025-07-10T09:02:05",
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 4.0,
                    "Nr_days_total": 0.5,
                },
                {
                    "Project_TS_Calendar_ID": "107c3979",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-06",
                    "Nr_hours_normal": 0.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": 4.0,
                    "Comment": "Zondag",
                    "Update": null,
                    "Last_change": "2025-07-10T09:02:29",
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 4.0,
                    "Nr_days_total": 0.5,
                },
                {
                    "Project_TS_Calendar_ID": "dffbdfcc",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-07",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
                {
                    "Project_TS_Calendar_ID": "70b11165",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-08",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
                {
                    "Project_TS_Calendar_ID": "30575f1e",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-09",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": null,
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
                {
                    "Project_TS_Calendar_ID": "2777ba0e",
                    "Project_TS_ID": "202507TSTSTAb211053c",
                    "Date": "2025-07-10",
                    "Nr_hours_normal": 8.0,
                    "Nr_hours_OT1": "",
                    "Nr_hours_OT2": null,
                    "Comment": null,
                    "Update": null,
                    "Last_change": null,
                    "Changed_by": "nico.marien@sisusync.app",
                    "ProjectTSEmail": null,
                    "Nr_hours_total": 8.0,
                    "Nr_days_total": 1.0,
                },
            ],
            "Related_exception_times": [
                {
                    "Exception_time_id": "02eb9c02",
                    "TS_ID": "202507TSTSTAb211053c",
                    "Project_exception_time_id": "fb6ceb72",
                    "Quantity": 5.0,
                    "Units": "Hours",
                    "Description": "Test exception time",
                    "Note": "22 juli",
                    "Update": null,
                    "last_change": "2025-07-10T09:18:57",
                    "changed_by": "nico.marien@sisusync.app",
                },
                {
                    "Exception_time_id": "4c5dffbe",
                    "TS_ID": "202507TSTSTAb211053c",
                    "Project_exception_time_id": "0dabfcf2",
                    "Quantity": 1.0,
                    "Units": "Days",
                    "Description": "Test exception time 2",
                    "Note": "23 juli",
                    "Update": null,
                    "last_change": "2025-07-10T09:20:37",
                    "changed_by": "nico.marien@sisusync.app",
                },
                {
                    "Exception_time_id": "e54b603d",
                    "TS_ID": "202507TSTSTAb211053c",
                    "Project_exception_time_id": "fb6ceb72",
                    "Quantity": 5.0,
                    "Units": "Hours",
                    "Description": "Test exception time",
                    "Note": "21/07/2025",
                    "Update": null,
                    "last_change": "2025-07-09T17:05:52",
                    "changed_by": "nico.marien@sisusync.app",
                },
            ],
        },
        "convertTo": "pdf",
        "timezone": "Europe/Paris",
        "lang": "en",
        "complement": {},
        "variableStr": "",
        "reportName": "document",
        "enum": {},
        "translations": {},
        "currencySource": "",
        "currencyTarget": "",
        "currencyRates": {},
        "hardRefresh": "",
    }
)

# Headers for Carbone
headers = {
    "Authorization": access_token,
    "Content-Type": "application/json",
    "Accept": "application/json",
}

# Make the POST request
carbone_api_url = f"https://api.carbone.io/render/{template_id}"
response = requests.post(carbone_api_url, headers=headers, data=json_payload)

# Print the raw response
print("Status code:", response.status_code)
print("Response JSON:", response.json())
